export { api, getToken, setToken, removeToken, ApiError } from './client'
export type { } from './types'

export { authApi }      from './endpoints/auth'
export { teachersApi }  from './endpoints/teachers'
export { studentsApi }  from './endpoints/students'
export { attendanceApi } from './endpoints/attendance'
export { complaintsApi } from './endpoints/complaints'
export { feesApi }      from './endpoints/fees'
export { homeworkApi }  from './endpoints/homework'
export { noticesApi }   from './endpoints/notices'
export { messagesApi }  from './endpoints/messages'
export { salaryApi }    from './endpoints/salary'
export { interviewsApi } from './endpoints/interviews'
export { classesApi }   from './endpoints/classes'
export { busesApi }     from './endpoints/buses'
export { reportsApi }   from './endpoints/reports'
