const router = require('express').Router()

router.use('/auth',        require('./authRoutes'))
router.use('/teachers',    require('./teacherRoutes'))
router.use('/students',    require('./studentRoutes'))
router.use('/attendance',  require('./attendanceRoutes'))
router.use('/complaints',  require('./complaintRoutes'))
router.use('/fees',        require('./feeRoutes'))
router.use('/homework',    require('./homeworkRoutes'))
router.use('/notices',     require('./noticeRoutes'))
router.use('/messages',    require('./messageRoutes'))
router.use('/salary',      require('./salaryRoutes'))
router.use('/interviews',  require('./interviewRoutes'))
router.use('/classes',     require('./classRoutes'))
router.use('/transport',   require('./busRoutes'))
router.use('/reports',            require('./reportRoutes'))
router.use('/student-categories', require('./studentCategoryRoutes'))
router.use('/sections',           require('./sectionRoutes'))
router.use('/exams',              require('./examRoutes'))
router.use('/certificates',       require('./certificateRoutes'))
router.use('/school-settings',    require('./schoolSettingsRoutes'))
router.use('/admin',              require('./adminRoutes'))

module.exports = router
